name: sislart
description: Dibuat Oleh Bigsu Team - 2023.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # BAWAAN FLUTTER JANGAN DI HAPUS
  network_image: ^0.1.1
  intl: ^0.18.1 # Date Time
  firebase_core: ^2.14.0 # Firebase Core
  firebase_auth: ^4.6.3 # Firebase - Authentication
  cloud_firestore: ^4.8.2 # Firebase - Cloud Firestore
  flutter_svg: ^2.0.7 # Svg Image
  fluttertoast: ^8.2.2 # Pop Up Toast
  google_fonts: ^4.0.0 # Fonts
  qr_flutter: ^4.1.0 # QR Generator
  google_maps_flutter: ^2.3.1 # Maps On Google
  flutter_speed_dial: ^7.0.0 # Multiple Floating Button
  percent_indicator: ^4.2.3 # Line Progress
  flutter_inappwebview: ^5.7.2+3 # WebView
  shared_preferences: ^2.2.0 # Save Data With Cache
  cached_network_image: ^3.2.3 # Image Network Save Cache
  flutter_polyline_points: ^1.0.0 # ArcGIS Line Route Maps
  flutter_cache_manager: ^3.3.1 # Menyimpan Data Di Cache
  dropdown_button2: ^2.0.0
  social_media_buttons: ^1.0.0
  url_launcher: ^6.0.12
  image_picker: ^1.0.1
  dio: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/appbar/
    - assets/images/icon/
    - assets/images/marker/
    - assets/images/splash/
    - assets/svg/appbar/
    - assets/svg/home/
    - assets/svg/stasiun/
    - assets/json/
